language: go

go:
  - tip

# Some tests write to /tmp but travis doesn't work so well with that. Set our
# own value TMPDIR so things like os.TempDir will use our custom location.
env:
  global:
    - TMPDIR=$TRAVIS_BUILD_DIR/tmp

# Install dependencies including test dependencies. We could just use `go get
# -t ./...` but not all examples are meant to compile.
install:
  - find . -name "*_test.go" -exec dirname {} \; | uniq | xargs go get -t -v

# Get a list of all directories with test files and test them.
script:
  - find . -name "*_test.go" -exec dirname {} \; | uniq | xargs go test
